apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-script" (include "evict-to-rollout.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/name: {{ include "evict-to-rollout.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  evict_to_rollout.sh: |
{{ (.Files.Get "files/evict_to_rollout.sh" ) | indent 4 }}


