apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "evict-to-rollout.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "evict-to-rollout.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "evict-to-rollout.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
            {{- with .Values.podLabels }}
            {{- range $k, $v := . }}
            {{ $k }}: {{ $v | quote }}
            {{- end }}
            {{- end }}
          {{- with .Values.podAnnotations }}
          annotations:
            {{- range $k, $v := . }}
            {{ $k }}: {{ $v | quote }}
            {{- end }}
          {{- end }}
        spec:
          serviceAccountName: {{ include "evict-to-rollout.serviceAccountName" . }}
          restartPolicy: OnFailure
          containers:
            - name: {{ include "evict-to-rollout.name" . }}
              image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["/bin/bash", "-c"]
              args: ["/scripts/evict_to_rollout.sh"]
              env:
                - name: ANNOTATION_KEY
                  value: {{ .Values.annotationSelector.key | quote }}
                - name: ANNOTATION_VALUE
                  value: {{ .Values.annotationSelector.value | quote }}
              volumeMounts:
                - name: script
                  mountPath: /scripts
              resources:
{{- toYaml .Values.resources | nindent 16 }}
          volumes:
            - name: script
              configMap:
                name: {{ printf "%s-script" (include "evict-to-rollout.fullname" .) | trunc 63 | trimSuffix "-" }}
                defaultMode: 0755
          {{- with .Values.nodeSelector }}
          nodeSelector:
{{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
{{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
{{- toYaml . | nindent 12 }}
          {{- end }}

